name: Unit Tests

on:
  - push

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        tuist_version: [3.12.1]
        
    steps:
      - uses: actions/checkout@v3
      - uses: tuist/tuist-action@0.13.0
        with:
          command: 'build'
          arguments: ''
          
      - name: "Run unit tests"
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          LC_CTYPE: en_US.UTF-8
        run: tuist test
