name: Unit Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: 14.0.1

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
        shell: bash

      - name: Fetch tuist dependencies
        run: |
          tuist fetch
        shell: bash

      - name: Tuist Warm Cache
        run: |
          tuist cache warm
        shell: bash
        
      - name: "Clean old workspace setup"
        run: |
          tuist clean

      - name: Generate project with tuist
        run: |
          tuist generate --no-open
        shell: bash
        
      - name: Testing iOS app
        run: tuist test
