name: Unit Tests

on:
  - push

jobs:
  build:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        tuist_version: [3.12.1]

    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13.4
      - name: Prepare
        run: |
          if [[ -d "$RUNNER_TEMP" ]]; then
            export TMPDIR="$RUNNER_TEMP"
          fi
          tmpdir=$(mktemp -d)
          pushd "$tmpdir"
          curl -OL https://github.com/tuist/tuist/releases/download/3.15.0/tuistenv.zip
          unzip tuistenv.zip
          popd
          echo "Tuist version: ${{ matrix.tuist_version }}"
          "$tmpdir/tuistenv" local "${{ matrix.tuist_version }}"
          "$tmpdir/tuistenv" generate -n
          rm -rf "$tmpdir"
      - name: Build
        run: |
          rm -rf DerivedData
          xcodebuild ARCHS=x86_64 -workspace MyProject.xcworkspace \
            -scheme TestHost -sdk iphonesimulator -configuration Debug \
            -derivedDataPath DerivedData clean build
